apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ksr4od54n-nodejs 
  janus-idp.io/tekton: ksr4od54n-nodejs
  backstage.io/kubernetes-id: ksr4od54n-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ksr4od54n-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml